name: Build

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            file: mcu-manager.exe
          - os: ubuntu-latest
            file: mcu-manager
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Upload release
        uses: actions/upload-artifact@v1
        with:
          name: release-${{ matrix.os }}
          path: build/release/${{ matrix.file }}
